### ISSUE TITLE
Integrate with ZIO Shield

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio-intellij#10]
https://github.com/zio/zio-shield

**Comment by shankarshastri** [comment]
@hmemcpy , I can pick this up. Should all the warnings as well be fixed as part of the same PR?

**Comment by hmemcpy** [comment]
Sure! That'd be fantastic, thanks! Though I'm not quite sure about the status of that project...

**Comment by shankarshastri** [comment]
@hmemcpy , Any thoughts on the warnings? As there are warnings as well?

**Comment by hmemcpy** [comment]
ZIO Shield is not being developed, last commit is March 2020. Closing this until it gets picked up again.
