### ISSUE TITLE
Suggest ZIO.none, ZIO.some, ZIO.left and ZIO.right

### ISSUE THREAD

**Issue by timaliberdov** [zio/zio-intellij#108]
Suggest replacing:
- UIO(None) with ZIO.none
- UIO(Some(x)) with ZIO.some(x)
- UIO(Left(x)) with ZIO.left(x)
- UIO(Right(x)) with ZIO.right(x)

**Comment by hmemcpy** [comment]
I believe some/none is already supported (https://github.com/zio/zio-intellij/issues/5) but I don't think it looks for the `apply` pattern, only `succeed`. Should be an easy fix :)
