### ISSUE TITLE
Suggest ZIO.traverse

### ISSUE THREAD

**Issue by guersam** [zio/zio-intellij#11]
`ZIO.collectAll(xs.map(f))` => `ZIO.traverse(xs)(f)`

**Comment by ghostdogpr** [comment]
Nice one 👍

**Comment by ghostdogpr** [comment]
Same with the `collectAllPar` version.
Btw `traverse` is an alias for `foreach`, maybe it's better to suggest the original?

**Comment by hmemcpy** [comment]
The more, the merrier. Will be a good documentation for deprecating later :)
BTW, there are several highlighting levels. The default, `WARNING` is the yellowish highlighting, e.g.:
![image](https://user-images.githubusercontent.com/601206/68123822-a3900980-ff16-11e9-8275-0650c4a1b1f3.png)

and the "weak warning", which is an underline:
![image](https://user-images.githubusercontent.com/601206/68123844-ad197180-ff16-11e9-9f01-5223f62afd0b.png)

It's all user-configurable, but it would be also nice to provide good defaults. Some of the suggestions might be too nitpicky.
