### ISSUE TITLE
Suggest tap

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-intellij#12]
`.flatMap(a => f(a).as(a))` => `.tap(f)`
`.flatMap(a => b.as(a))` => `.tap(_ => b)`

Similarly, `tapError` and `tapBoth`.

**Comment by zalbia** [comment]
Working on this.

**Comment by hmemcpy** [comment]
Can you give me an example of `.tapBoth`? Is it `flatMap` followed by `flatMapError`?
