### ISSUE TITLE
@accessible not being applied

### ISSUE THREAD

**Issue by threeseed** [zio/zio-intellij#123]
IntelliJ: 2020.1.2
ZIO-IntelliJ: 2020.1.0.8 (enabled)

As you can see in screenshots methods generated by @accessible are not being recognised by IntelliJ.

<img width="742" alt="Screen Shot 2020-07-09 at 11 27 35 am" src="https://user-images.githubusercontent.com/657041/86986629-74cddf80-c1d7-11ea-9090-2f18197db0ca.png">

<img width="417" alt="Screen Shot 2020-07-09 at 11 27 52 am" src="https://user-images.githubusercontent.com/657041/86986636-78616680-c1d7-11ea-871c-302720c5b64c.png">

**Comment by timaliberdov** [comment]
This issue was fixed in https://github.com/zio/zio-intellij/pull/43. The next release is coming soon 🙂

**Comment by threeseed** [comment]
@timaliberdov .. Have verified this is fixed in master. Closing.

P.S. Such a great project. Thanks for everything !
