### ISSUE TITLE
IntelliJ IDEA shows Any instead of a correct type in parameters of a service's method

### ISSUE THREAD

**Issue by vsuharnikov** [zio/zio-intellij#129]
## How it looks like

![Screen Shot 2020-07-24 at 08 39 52](https://user-images.githubusercontent.com/2654820/88363691-7d9ee380-cd89-11ea-8ae0-878a73b4b83b.png)

## How to reproduce

It happens only for classes in a package object.
The problem appeared in the last or in a previous release of the plugin.

```scala
// bug/domain/package.scala
package test
package object domain {
  // Works fine if I move this to the own file.
  // But I can' use newtype ( https://github.com/estatico/scala-newtype ) then
  case class Foo(x: Int)
}

// bug/services/SomeService.scala
package bug.services

import bug.domain.Foo
import zio.Task
import zio.macros.accessible

@accessible
object SomeService {
  trait Service {
    def run(arg: Foo): Task[Unit]
  }
}

// bug/Usage.scala
package bug

import bug.services.SomeService

object Usage {
  SomeService.run() // <-- here we see Any instead of Foo
}
```

## Versions

IntelliJ IDEA 2020.1.4 (Ultimate Edition)
Build #IU-201.8743.12, built on July 21, 2020
Runtime version: 11.0.7+10-b765.65 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6

## Plugins

Scala: 2020.1.41
ZIO for IntelliJ: 2020.1.0.9

**Comment by hmemcpy** [comment]
Should be noted this looks related to `@accessible` support

**Comment by zawlazaw** [comment]
This does not just affect classes defined in package objects, but classes defined in _any_ object (tested with plugin version 2021.2.14.0 and zio version 2.0.0-RC5).
For example, if specifying a domain api the way as suggested for a zio-http middleware:
```
sealed trait UsersResponse
object UsersResponse {
  final case class Got(user: User)     extends UsersResponse
  final case class Created(user: User) extends UsersResponse
}
```
Then any service that returns any response (e.g. `Got` or `Created`) shows errors in IntelliJ as if it were returning `Any`, although compilation and execution works fine.

The only workaround I can see right now is to define all classes outside of any object (e.g. in their own package for encapsulation).

**Comment by myazinn** [comment]
Fixed [here ](https://github.com/zio/zio-intellij/pull/433), will be released soon
Sorry it took so long. I've got no idea how I didn't notice it earlier
![image](https://user-images.githubusercontent.com/28982711/234919684-88b414f5-31c2-45b0-bb64-062ee6cce2d9.png)
