### ISSUE TITLE
'Find usages' feature for macro created classes with @accessible

### ISSUE THREAD

**Issue by aartigao** [zio/zio-intellij#131]
The usage of macros for accessor methods reduce a lot the boilerplate in the module pattern services.

One thing that I noticed is that I use a lot the 'Find usages' feature in order to check which classes are using it.

Given the following code:

```scala
package com.foo.project

import zio._
import zio.macros.accessible

object Main extends App {

  override def run(args: List[String]): ZIO[ZEnv, Nothing, ExitCode] =
    Foo.foo(args.headOption.getOrElse("bar"))
      .map(c => ExitCode(c))
      .provideCustomLayer(Foo.live)

}

@accessible
object Foo {

  type Foo = Has[Service]

  trait Service {

    def foo(s: String): UIO[Int]

  }

  val live: ULayer[Foo] = ZLayer.succeed((s: String) => UIO.succeed(s.length))

}
```

If I want know who is using `def foo(s: String): UIO[Int]` with `Ctrl + Mouse left` or `Alt + Shift + 7` in Linux, I can't.

Whereas:

```scala
package com.foo.project

import zio._
import zio.macros.accessible

object Main2 extends App {

  override def run(args: List[String]): ZIO[ZEnv, Nothing, ExitCode] =
    Foo.foo(args.headOption.getOrElse("bar"))
      .map(c => ExitCode(c))
      .provideCustomLayer(Foo.live)

}

object Foo {

  type Foo = Has[Service]

  trait Service {

    def foo(s: String): UIO[Int]

  }

  def foo(s: String): URIO[Foo, Int] = URIO.accessM(_.get.foo(s))

  val live: ULayer[Foo] = ZLayer.succeed((s: String) => UIO.succeed(s.length))

}
```

It works as expected. I know it's a tricky one to solve, but let's discuss 😄

**Comment by myazinn** [comment]
I think it should also search for the accessor methods when they are explicitly written.
It would be nice if the plugin will ask whether the user wants to find all accessor methods. Just like how it's done for the usages of the base trait / class.
