### ISSUE TITLE
Rewrite `*>` chain expressions to `for`

### ISSUE THREAD

**Issue by neko-kai** [zio/zio-intellij#14]
```scala
x *> 
y *> 
z
```
to 
```scala
for {
  _ <- x
  _ <- y
  r <- z
} yield r
```

Oftentimes a chain starts small, with one or two actions chained with `*>`. When such a chain grows larger it becomes more suitable to write it as a for-comprehension.

**Comment by hmemcpy** [comment]
Maybe vice-versa, too
