### ISSUE TITLE
ZIO.foreach_ replacement erroneously discards code

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio-intellij#146]
Before:
![image](https://user-images.githubusercontent.com/601206/93018238-e3b02600-f5d6-11ea-9845-2553da9c6fde.png)

After:
![image](https://user-images.githubusercontent.com/601206/93018241-e7dc4380-f5d6-11ea-9f8c-50736ea0ab59.png)

Introduced in #135 

FYI @timaliberdov @myazinn

**Comment by myazinn** [comment]
Oops :) I will try to fix it as soon as possible.
