### ISSUE TITLE
[Feature Request] IJ Test Runner doesn't show successful results

### ISSUE THREAD

**Issue by bertlebee** [zio/zio-intellij#149]
The standard zio test test runner shows a tree of successful suites/tests. IJ test runner only shows failed tests.

It would be good if the IJ test runner could show the complete tree of tests that were run, ideally with all successful suites collapsed by default.

Happy to help with this if someone can point me in the right direction - I've never worked with IJ plugins before!

**Comment by hmemcpy** [comment]
I'm fairly certain it does, but IntelliJ (for some reason) does not show successful tests by default. Can you make sure this button is checked?
![image](https://user-images.githubusercontent.com/601206/93028968-5691bf00-f620-11ea-82a2-62c88df51689.png)

Aside: the integrated test runner for ZIO Tests currently needs to be installed as a library reference. Hopefully it will be downloaded automagically in the future. Please see https://github.com/zio/zio-test-intellij

**Comment by bertlebee** [comment]
Sorry, user error :( button clicked and behaving as I'd expect the default behaviour to be. Thanks for your help, and excellent work on the test runner! testing is much more enjoyable without the command line :)
