### ISSUE TITLE
Publish to IntelliJ plugin repository

### ISSUE THREAD

**Issue by alexvanolst** [zio/zio-intellij#16]
At some point this plugin should be published to the IntelliJ plugin repository.

Instructions can be found here: https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/publishing_plugin.html

I'm assuming this is something @hmemcpy will want to do himself, but if not let me know and I can.

**Comment by hmemcpy** [comment]
Yes, I intend to publish this when we have a CI set up and versioning figured out... just need to get to it! Pretty soon, though!
