### ISSUE TITLE
Test runner stuck

### ISSUE THREAD

**Issue by leszekgruchala** [zio/zio-intellij#171]
I had a test case that causes the IDEA ZIO runner to stuck. The same test passes executed through SBT shell or without `zio-test-sbt

<img width="1288" alt="Screen Shot 2020-10-08 at 14 36 57" src="https://user-images.githubusercontent.com/89165/95584165-88d6e680-0a3d-11eb-96dc-d4f971b5360e.png">

If I remove zio-test-intellij the test is passing when run from UI.
The stuck problem is always reproducible for me with this test https://scastie.scala-lang.org/FjdpBRJGRTqRvKNKj4GXMw
I have zio 1.0.2 and `"dev.zio" %% "zio-test-intellij" % "1.0.1" % Test`

I use IDEA 2020.2.3 ultimate, idea runs on built-in JDK. ZIO for IntelliJ plugin 2020.2.1.1

**Comment by leszekgruchala** [comment]
@hmemcpy  ZIO for IntelliJ plugin 2020.2.1.2 no longer blocks and passes this test. But I have still a few other tests that are failing when executed through `zio-test-intellij`. I use zio mocks and many other tests work, but just a few of them are failing with `unsatisfied expectations`, while with sbt shell they are passing even with `TestAspect.nonFlaky`.
What can I do to help you check and fix this issue?

**Comment by hmemcpy** [comment]
Thanks for the update, and sorry about the trouble :(
The only reason I can think of that the intellij runner might not work the same as the sbt shell is applying custom aspects. Maybe the intellij runner is missing some of them. Now I have somewhere new to look. Will update!

**Comment by hmemcpy** [comment]
I realize this is nearly a year after the fact, but I think I managed to (finally!) fix the aspects issue. Unfortunately, this is only for the ZIO 1.0.12 runner. If possible (and, if still relevant), please update your ZIO and let me know if you're still seeing those issues. In the meantime, I'm closing this issue...

Thank you!
