### ISSUE TITLE
identify ZIO value discard as a warning

### ISSUE THREAD

**Issue by phderome** [zio/zio-intellij#176]
If I construct an expression of type `UIO[URIO[Blocking, Unit]]` and it gets resolved by the compiler as type `UIO[Unit]` I am discarding an effect I care about (`URIO[Blocking, Unit]]`) and this may very well be unintentional.

My typical case was when using `map` accidentally instead of `flatMap` for example having `yield` in a `for` comprehension returning a `ZIO` effect instead of pushing up that evaluation with the other `flatMap` of the `for` comprehension.

**Comment by timaliberdov** [comment]
I'm pretty sure we have an inspection to detect and warn about yielding a `ZIO` effect in a `for` comprehension. Anyway, there are more corner cases. I'll look into it. Thank you!
