### ISSUE TITLE
Incorrect suggestion to remove schedules

### ISSUE THREAD

**Issue by threeseed** [zio/zio-intellij#199]
For this line of code:
```
vertx.sendMessage("message").fork.repeat(Schedule.spaced(5.second).forever).provide(Has(clock)).unit
```

It shows the following incorrect suggestion to remove the repeat:
<img width="638" alt="Screen Shot 2020-12-02 at 8 49 11 am" src="https://user-images.githubusercontent.com/657041/100801595-4ef1f180-347c-11eb-80e6-c7cb841d6b3f.png">

**Comment by hmemcpy** [comment]
Hmm, thanks! Sorry about that, will look into it! In the meantime, you can disable this warning if it bothers you.
