### ISSUE TITLE
catchAll(_ => ZIO.unit) -> .ignore

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio-intellij#2]

**Comment by hmemcpy** [comment]
Hmm, should I revert this, then?

**Comment by hmemcpy** [comment]
Hmm, should I rever this, then, @ghostdogpr?

**Comment by ghostdogpr** [comment]
Yeah maybe for now. I’ll create an issue to make it consistent with `option` and require `sandbox` to recover from unchecked failures. You can put it back once it’s done (unless that change is rejected for some reason). Sorry for the wrong suggestion 😅

**Comment by hmemcpy** [comment]
No worries! This is quite an educational way to learn ZIO :)

**Comment by ghostdogpr** [comment]
Fixed :) https://github.com/zio/zio/pull/2148

**Comment by hmemcpy** [comment]
Does this mean the suggestion is still valid? :)

**Comment by ghostdogpr** [comment]
Yep. `ignore` no longer catches unchecked failures so it’s equivalent to this `catchAll`

**Comment by hmemcpy** [comment]
Sweet, then I have nothing to do :)
