### ISSUE TITLE
SimplifyUnitInspection suggests to replace .forkDaemon.unit with .unit

### ISSUE THREAD

**Issue by evis** [zio/zio-intellij#211]
zio-intelilj version: 2020.3.3.1

Code to reproduce bug:

```scala
import zio._

object SimplifyUnitInspectionTest extends zio.App {

  override def run(args: List[String]): URIO[ZEnv, ExitCode] = {
    val sideEffect = console.putStrLn("reproduce bug")
    (sideEffect *> sideEffect.forkDaemon.unit).exitCode
  }
}
```

This code prints "reproduce bug" twice.

Expected behavior: plugin doesn't suggest to refactor this code.

Actual behavior: plugin suggests to replace `sideEffect *> sideEffect.forkDaemon.unit` with `sideEffect.unit`. This refactoring changes code's behavior.

Workaround: put `//noinspection SimplifyUnitInspection` comment.

**Comment by hmemcpy** [comment]
Ugh. Thank you, I'll take a look!
