### ISSUE TITLE
Support Scala 3 test runner

### ISSUE THREAD

**Issue by crfeliz** [zio/zio-intellij#221]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_3.0:1.0.3"
Cause:
java.lang.RuntimeException: unresolved dependency: dev.zio#zio-test-intellij_3.0;1.0.3: not found
```
### Additional information:
<details>

ZIO plugin version: 2020.3.4.0
Scala plugin version: 2020.3.660
ZIO version(s): 1.0.3
Scala version(s): 3.0.0-M3
IntelliJ version: IntelliJ IDEA 2020.3.1
Build #IU-203.6682.168
Java version: 11.0.9.1+11-b1145.63
Operating System: x86_64 Mac OS X (10.14.6, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Oh yikes!

The good news - the error reporter is working, thank you for that!
The bad news - it doesn't find a test runner for Scala 3... and I believe I don't compile it currently for it :(

Thank you for the report, I'll make sure it's available ASAP.

In the meantime, please ignore the prompt.

One more question: is this a dotty-only project or is it a cross-compilation?

**Comment by crfeliz** [comment]
Thanks for the quick response! It *was* a dotty only project at the time of the report. I've since switched back to scala 2.13 so this is no longer an issue for me specifically. And yes - the error reporter did work perfectly!

**Comment by hmemcpy** [comment]
I believe this is now working, and can be closed!
