### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by wevogt** [zio/zio-intellij#224]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_2.12:1.0.0-RC18"
Cause:
java.lang.RuntimeException: unresolved dependency: dev.zio#zio-test-intellij_2.12;1.0.0-RC18: not found
```
### Additional information:
<details>

ZIO plugin version: 2020.3.4.0
Scala plugin version: 2020.3.18
ZIO version(s): 1.0.0-RC18
Scala version(s): 2.12.10
IntelliJ version: IntelliJ IDEA 2020.3.1
Build #IU-203.6682.168
Java version: 11.0.9.1+11-b1145.63
Operating System: x86_64 Mac OS X (10.16, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Oh wow. Seems like you're using a very old (pre-release) version of ZIO. Please upgrade your ZIO to at least 1.0.0.
