### ISSUE TITLE
Set @accessor name as a reference, so it can be renamed together with the members

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio-intellij#23]
Need to figure out how to do it... @alexvanolst

**Comment by alexvanolst** [comment]
This sounds potentially tricky to do.  There is a `MemberInplaceRenameHandler ` but I'm not sure how one would tie the rename to the annotation constructor string literal.

I think I a good starting point would be to disallow renaming for both the helper (">") and the Accessor object with an appropriate message pointing out that this is generated code.

The lombok plugin does this here:
https://github.com/mplushnikov/lombok-intellij-plugin/commit/710e06b658022d6fc7dd5b2e00af73ea687222d2

Then perhaps open another issue to investigate getting the helper renaming to work.

**Comment by hmemcpy** [comment]
I spiked this feature, however, I think the goal is to eventually [move away from the `>` pattern](https://github.com/zio/zio-macros/issues/101) in favor of `ZLayer`s. I'm closing this for now.
