### ISSUE TITLE
"Create new ZIO project" fails with error "Could not parse version 1.0.4-2"

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-intellij#241]
I tried to create a new project.

I the list of possible Scala project bases, there's "sbt", "dotty", etc. and there's "ZIO project (with sbt)". 

<img width="914" alt="Screenshot 2021-02-06 at 15 48 49" src="https://user-images.githubusercontent.com/1193670/107109253-d56aeb00-6892-11eb-8eaa-eb48374ab1b4.png">

Perfect! That's exactly what I wanted 🥳

But when I complete the next form, whichever version of ZIO I choose here:
<img width="914" alt="Screenshot 2021-02-06 at 15 45 03" src="https://user-images.githubusercontent.com/1193670/107109278-0fd48800-6893-11eb-8f66-0eceaf45d2e3.png">

The project creation fails with the following error:

<img width="389" alt="Screenshot 2021-02-06 at 15 42 10" src="https://user-images.githubusercontent.com/1193670/107109283-1c58e080-6893-11eb-8e55-946e89098fb1.png">

I'm using the last version of IntelliJ Ultimate and my plugins are up-to-date:
<img width="686" alt="Screenshot 2021-02-06 at 15 51 34" src="https://user-images.githubusercontent.com/1193670/107109293-44e0da80-6893-11eb-9e1d-642db64c7971.png">

🤔

**Comment by guizmaii** [comment]
Already fixed here: https://github.com/zio/zio-intellij/pull/239

**Comment by hmemcpy** [comment]
Thank you for the report! Until it comes available on the marketplace, you can download it directly from here:

https://plugins.jetbrains.com/plugin/13820-zio-for-intellij/versions/stable/110025
