### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by justinhj** [zio/zio-intellij#244]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_2.13:1.0.0-RC18"
Cause:
java.lang.RuntimeException: unresolved dependency: dev.zio#zio-test-intellij_2.13;1.0.0-RC18: not found
```
### Additional information:
<details>

ZIO plugin version: 2020.3.5.1
Scala plugin version: 2020.3.672
ZIO version(s): 1.0.0-RC18
Scala version(s): 2.13.1
IntelliJ version: IntelliJ IDEA 2020.3.2
Build #IC-203.7148.57
Java version: 11.0.9.1+11-b1145.77
Operating System: x86_64 Mac OS X (10.16, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Hey, sorry about this. But seems you're targeting an old ZIO (RC18) - and the test runner wasn't compiled for that version. Any specific reason you're not upgrading?

**Comment by justinhj** [comment]
Was just opening up an old project, probably shouldn't have just hit the report button :D I'll close this.
