### ISSUE TITLE
Not detecting unused expression in zio-test specs?

### ISSUE THREAD

**Issue by zalbia** [zio/zio-intellij#249]
**Expected behavior:** Should detect unused expression, though I'm not sure if intended
**Actual behavior:** Unused expression not detected

**Platform:**
- Windows 10 (2004)
- Intellij 2020.3
- zio-intellij  2020.3.5.1
- Scala 2.13.5

Minimal reproduction:

```scala
import zio.test._

object Repro extends DefaultRunnableSpec {
  def spec = suite("Repro") {
    testM("foo") { ??? } // undetected unused expression
    testM("bar") { ??? }
  }
}
```

**Comment by hmemcpy** [comment]
Hmm. In the default spec, the `suite` expects a varargs list of tests, separated by commas. I don't think this would even compile, and intellij would definitely paint it all as red as a Christmas tree...
Not sure `suite(...) { ... }` even works (need to check), you have to place it in parentheses.

The new ZIO has a `DefaultMutableRunnableSpec` where you can place top-level `test`/`testM`s without separating them by commas.

Either way, let me see if I could detect such missing commas and offer to add them!

**Comment by zalbia** [comment]
It compiles for me, [here it is](https://scastie.scala-lang.org/zecDT3OATumfjFnEnu09PA) in Scastie. This boils down to my misuse of `specs: Spec[R, E, T]*`. Like you said, it should be parens instead of curly brackets. So what ends up happening is only the last test gets run, which in the Scastie is shown as the Fiber failing on line 6, but not on line 5.

**Comment by myazinn** [comment]
Closed [here](https://github.com/zio/zio-intellij/pull/411).
![image](https://user-images.githubusercontent.com/28982711/226195958-eda7d4de-e441-477d-bfff-ae2fb1b73aef.png)

**Comment by hmemcpy** [comment]
I think this might not be related. The + operator is for zio test in 2.0, the ZIO 1 tests needed to be comma-separated AFAIK

**Comment by myazinn** [comment]
@hmemcpy seems to work fine with ZIO 1.0.17 (haven't checked other lower versions)
![image](https://user-images.githubusercontent.com/28982711/226205275-9da86d74-3780-4154-947b-6df9b36b43b8.png)
