### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by Raiv** [zio/zio-intellij#251]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_2.12:1.0.0-RC17"
Cause:
java.lang.RuntimeException: unresolved dependency: dev.zio#zio-test-intellij_2.12;1.0.0-RC17: not found
```
### Additional information:
<details>

ZIO plugin version: 2020.3.5.1
Scala plugin version: 2020.3.21
ZIO version(s): 1.0.0-RC17
Scala version(s): 2.12.10
IntelliJ version: IntelliJ IDEA 2020.3.3
Build #IU-203.7717.56
Java version: 11.0.10+8-b1145.96
Operating System: amd64 Linux (5.4.0-67-generic, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Yeah, sorry about this, the runner support was added to a later version. This seems to be a very old RC17. Please upgrade the project if possible...
