### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by apavlychev** [zio/zio-intellij#253]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_3.0.0-RC1:1.0.3"
Cause:
java.lang.RuntimeException: unresolved dependency: dev.zio#zio-test-intellij_3.0.0-RC1;1.0.3: not found
```
### Additional information:
<details>

ZIO plugin version: 2020.3.5.1
Scala plugin version: 2020.3.675
ZIO version(s): 1.0.3
Scala version(s): 3.0.0-RC1
IntelliJ version: IntelliJ IDEA 2020.3.3
Build #IC-203.7717.56
Java version: 11.0.10+8-b1145.96
Operating System: amd64 Linux (5.4.0-70-generic, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Sorry about this. The Scala 3 support for the runner was only added in ZIO 1.0.5. Please upgrade your project, if possible, and try again...
