### ISSUE TITLE
Prevent test runner prompt in projects with old ZIO versions

### ISSUE THREAD

**Issue by timaliberdov** [zio/zio-intellij#259]
Since we're getting a lot of related issues, I think it's time to introduce some version checking in the test runner code 🙂

Test runner was first released for RC18-2, so there's no point in trying to download it for RC18-1 and older.

**Comment by timaliberdov** [comment]
Probably will have to set an upper bound too...

**Comment by hmemcpy** [comment]
Lol good idea!
