### ISSUE TITLE
"Nothing here" shown in test run dropdown menu

### ISSUE THREAD

**Issue by mikrasilnikov** [zio/zio-intellij#265]
![zio-test-nothing](https://user-images.githubusercontent.com/17156630/116149667-1a145e80-a6eb-11eb-9930-355a0e1a53c1.png)

This happens in a generic project:

build.properties
```
sbt.version = 1.5.0`
```

build.sbt
```
name := "zio-test-intelij"
version := "0.1"
scalaVersion := "2.13.5"

libraryDependencies ++= Seq(
  "dev.zio" %% "zio-test"     % "1.0.6" % "test",
  "dev.zio" %% "zio-test-sbt"  % "1.0.6" % "test",
)
```

code
```scala
import zio.test._
import zio.test.Assertion._

class TestSuite extends DefaultRunnableSpec {
  def spec =
    suite("TestSuite") (
        test("Should pass") {
          assert(())(anything)
        }
    )
}
```

I'm using 

- Intellij Community 2021.1
- ZIO for IntelliJ 2021.1.6.0
- AdoptOpenJDK-11.0.11+9

**Comment by hmemcpy** [comment]
Took me a second to see it, but yeah - your `class` should be an `object`!

I make this mistake myself on occasion, and I'll use this opportunity to detect those situations. Thanks!

**Comment by mikrasilnikov** [comment]
Thank you )

**Comment by hmemcpy** [comment]
Finally fixed this particular landmine :) Fix coming soon!

![image](https://user-images.githubusercontent.com/601206/121262195-66db7f80-c8bc-11eb-81cc-2dcd9488536e.png)

![image](https://user-images.githubusercontent.com/601206/121262225-70fd7e00-c8bc-11eb-9ce6-feb22d9db7f4.png)

![image](https://user-images.githubusercontent.com/601206/121262242-78bd2280-c8bc-11eb-9010-1eacdf40d64a.png)
