### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by swoogles** [zio/zio-intellij#268]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_3.0.0:1.0.8"
Cause:
java.lang.RuntimeException: unresolved dependency: dev.zio#zio-test-intellij_3.0.0;1.0.8: not found
```
### Additional information:
<details>

ZIO plugin version: 2021.1.6.0
Scala plugin version: 2021.1.384
ZIO version(s): 1.0.8
Scala version(s): 3.0.0
IntelliJ version: IntelliJ IDEA 2021.1.1
Build #IU-211.7142.45
Java version: 11.0.10+9-b1341.41
Operating System: amd64 Linux (5.4.97-1-manjaro, amd64)
JVM version: Dynamic Code Evolution 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Sorry, this seems to be due to how dependencies are resolved for Scala 3. Please see https://github.com/zio/zio-intellij/issues/266. The [early build](https://plugins.jetbrains.com/plugin/13820-zio-for-intellij/early-access-program-eap) fixing this problem should be available shortly.
