### ISSUE TITLE
Wrong suggestion on catchAll converting a failure

### ISSUE THREAD

**Issue by domdorn** [zio/zio-intellij#274]
![grafik](https://user-images.githubusercontent.com/100349/120931812-8a070300-c6f3-11eb-9278-ce4e21488bcf.png)

The plugin offers a wrong suggestion which would change semantics. 
```scala
        val bla: ZIO[Logging, GetTimeseriesDataFailedResponse, GetTimeseriesDataSucceededResponse] = for {
          e <- ZIO.fromEither(res.body).catchAllCause(c => zio.logging.log.error("failed to decode success response from timeseries-service", c) *> ZIO.fail(fallbackLeft(correlationId, request)))
          v <- readValue[GetTimeseriesDataSucceededResponse](e).catchAll(x => ZIO.fail(fallbackLeft(correlationId, request)))
        } yield v
        bla

```

**Comment by hmemcpy** [comment]
Thanks for this!

Your code snippet is a bit different, it uses `catchAllCause` which is currently not inspected by the plugin.
In the original snippet, I suppose the suggestion could be:

```scala
ZIO.fromEither(res.body).tapError(x => zio.logging.log.error("failed to decode success response from timeseries-service")).orElseFail(fallbackLeft(correlationId, request))
```
which would be equivalent, however I'm not so sure it's more readable. Perhaps it's worth disabling this suggestion for more complex error handling (i.e. anything that doesn't just fail with the `x`).
This is what the feature is intended to do:

```scala
program.catchAll(ex => logger.logError(ex) *> ZIO.fail(ex)) -> program.tapError(ex => logger.logError(ex))
```
