### ISSUE TITLE
zio-test offers wrong matcher

### ISSUE THREAD

**Issue by domdorn** [zio/zio-intellij#278]
<img width="938" alt="grafik" src="https://user-images.githubusercontent.com/100349/121246650-b06aa100-c8a1-11eb-906c-62dd95bc3342.png">

```scala

  val publishDataShouldFailTest = testM("publishData should return a error on non successfull http status") {
    for {
      _ <- whenRequestMatches(
        r => r.uri.toString() == ("http://localhost:8080/api/rtd/results") &&
          r.headers("X-Correlation-ID").head.equals(c.id.toString)
      ).thenRespondServerError()
      v <- TimeseriesDataClient.publishData(c, publishDataRequest).either
    } yield assert(v)(equalTo(Left(PublishDataFailedResponse(c, "Internal server error"))))
  }

```

gets changed to 
<img width="943" alt="grafik" src="https://user-images.githubusercontent.com/100349/121246792-cc6e4280-c8a1-11eb-90f2-01eb7e175009.png">

but no matcher `beLeft` exists in zio-test.

Plugin Version: 2021.1.9.1

**Comment by timaliberdov** [comment]
Hmm... it looks like the Scala plugin confused zio-test for specs2 and suggests a replacement for specs2 `beLeft` matcher.

https://github.com/JetBrains/intellij-scala/blob/69f62fe91859c9e3c1da42d6aa7d0fc13d62d19c/scala/scala-impl/src/org/jetbrains/plugins/scala/codeInspection/specs2/BuiltinMatcherExistsInspection.scala

@hmemcpy сan we override this somehow or is it better to create a ticket/PR in the Scala plugin?

**Comment by timaliberdov** [comment]
Haven't looked at it properly yet. I'll try to figure it out on the weekend.

**Comment by hmemcpy** [comment]
Thanks for the report, but I believe this is a long standing IntelliJ/scala plugin bug. I've seen it offer the specs2 matchers in unrelated tests many times, but I never bothered following it up with a repro :)

However, this might be a good opportunity to point this to someone from the Scala plugin team who works on the test integration :)

**Comment by hmemcpy** [comment]
So yeah, took a look at `BuiltinMatcherExistsInspection` in the scala plugin - unless I'm mistaken, it's not checking anywhere that it should only run when the TestFramework is specs2. I've let the developer responsible know, it will probably be fixed on the scala plugin side https://youtrack.jetbrains.com/issue/SCL-19140

**Comment by hmemcpy** [comment]
In the meantime, as a workaround, you can uncheck the specs2 matchers suggestion in the Preferences:
![image](https://user-images.githubusercontent.com/601206/121340074-d9357980-c927-11eb-9a50-61389c089e11.png)

**Comment by domdorn** [comment]
So as this is a problem with the intellij-scala plugin and I guess we cannot disable matchers for other plugins, I'm closing this. Thanks for the help!
