### ISSUE TITLE
Implement @mockable support

### ISSUE THREAD

**Issue by the-pavels** [zio/zio-intellij#28]
ZIO guidelines suggest using zio-macros to generate helper methods for service mocking. 
It would be great to add hints in Intellij Idea for the generated code.

**Comment by alexvanolst** [comment]
I'll add support for this.

**Comment by c-solo** [comment]
HI, is there any progress? Estimation?

**Comment by timaliberdov** [comment]
> HI, is there any progress? Estimation?

Hi, thank you for the reminder! I'll take a look. Hopefully, I'll be able to get to it this week.
