### ISSUE TITLE
aspects not taken into work, no way to run suite multiple tests with TestAspect.sequential

### ISSUE THREAD

**Issue by kuzkdmy** [zio/zio-intellij#283]
aspects are not taken into work, so there is no way to run suite with multiple tests when TestAspect.sequential is required

**Comment by hmemcpy** [comment]
Thanks for the report. I made some changes to the test runner that ensures aspects are taken into account. Unfortunately, this is for ZIO 1.0.12. If relevant, could you please upgrade your ZIO version and try with the new runner?

In the meantime, I'm closing this issue.

Thanks!

**Comment by ollyw** [comment]
I got the chance to test this. Good news is that aspects applied to the Suite works well. The downside is that with the latest EAP + ZIO plugin + test runner + zio 1.0.0.12, it seems that the testrunner field in base classes of traits are now ignored. Take this simplified example that we use to ensure that unit tests that fail in CI are repeatable for each CI job, but different for each:
```
object BespokeRunnableSpec {
  private lazy val getSeed = sys.env.get("CI_JOB_ID").flatMap(_.toLongOption).getOrElse(defaultSeed)

  private lazy val testRunner: TestRunner[TestEnvironment, Any] = TestRunner(
    executor = TestExecutor.default(testEnvironment >+> (for {
      seed <- UIO(getSeed)
      _    <- TestRandom.setSeed(seed)
    } yield ()).toLayer)
  )

abstract class BespokeRunnableSpec extends DefaultRunnableSpec {

  override def runner: TestRunner[TestEnvironment, Any] = testRunner
}
```
The above example has worked for a long while, until the latest version with fixed aspects

If you have any suggestions how to do such a thing so it is compatible with sbt and the Intelli zio plugin, now and for the future, I would be really grateful

**Comment by hmemcpy** [comment]
Oh damn :(

The test runner executable calls `withReporter` on the default `testRunner` instance to replace the actual reporter with one capable of rendering IntelliJ-specific output. I will have to check if I take custom `testRunner` into account. Sorry about this :(

The good news is that this functionality is built into ZIO 2.0, so there will be no difference in how it's executed - so the custom runner component will no longer be required. Until then... let's hope I manage to fix it for good! Thanks, I'll reopen this issue.

**Comment by hmemcpy** [comment]
Hi @ollyw 

I just tried this snippet on my machine:
```scala
object BespokeRunnableSpec {
  private lazy val getSeed = sys.env.get("CI_JOB_ID").flatMap(_.toLongOption).getOrElse(123454321L)

  private lazy val testRunner: TestRunner[TestEnvironment, Any] = TestRunner(
    executor = TestExecutor.default(testEnvironment >+> (for {
      seed <- UIO(getSeed)
      _ <- ZIO.debug("Hello from custom test runner") // <---- custom line
      _ <- TestRandom.setSeed(seed)
    } yield ()).toLayer)
  )
}

abstract class BespokeRunnableSpec extends DefaultRunnableSpec {
  override def runner: TestRunner[TestEnvironment, Any] = testRunner
}

object Spec extends BespokeRunnableSpec {
  def spec = suite("Hello") {
    testM("Trying random") {
      for {
        seed <- TestRandom.getSeed
        _ <- ZIO.debug(s"The seed is: $seed")
      } yield assertCompletes
    }
  }
}
```

I get the output:
```
Testing started at 14:03 ...
Hello from custom test runner
The seed is: 123454321
```

So this *seem* to be working just fine with the latest runner and ZIO 1.0.12.

Is there anything I'm missing/did wrong for this test?

**Comment by hmemcpy** [comment]
I'm closing stale/old issues. I believe this was fixed, please report it again if the problem happens again. 🙏
