### ISSUE TITLE
Fix serviceWith inspection

### ISSUE THREAD

**Issue by timaliberdov** [zio/zio-intellij#297]
Example:

```scala
package com.example

import zio._

object Example {
  trait Redis {
    def read: UIO[Unit]
    def read(n: Int): UIO[Unit]
  }
  type RedisService = Has[Redis]

  ZIO.service[Redis].flatMap { redis =>
    // random import
    import zio.duration._

    for {
      _ <- redis.read
      _ <- redis.read(5)
    } yield ()
  }

  ZIO.service[Redis].flatMap { redis =>
    redis.read *> console.putStrLn("hello")
  }.provideSomeLayer[Has[Redis]](console.Console.live)

}
```

The first example trims expression to the first line if there's some import inside flatMap body. Without import it works fine.
The second one produces wrong types. 

https://user-images.githubusercontent.com/8186312/124019747-16a29980-d9f2-11eb-985b-26f1aae7f238.mov

**Comment by hmemcpy** [comment]
Yikes! Better combine this with fixing #292

**Comment by hmemcpy** [comment]
Uff, just encountered something like this myself. Better fix it finally :)
