### ISSUE TITLE
Test runner picks up additional tests, even though only one is being executed

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio-intellij#30]
Example: caliban

src/test/scala/caliban/execution/ExecutionSpec.scala

running `testM("fragment")` runs both "fragment" and "inline fragment"

(this is most likely a bug in the args parsing in ZTestRunnerHost

**Comment by hmemcpy** [comment]
Update: this is the default ZIO Test behavior. Perhaps it will change by including wildcard support? https://github.com/zio/zio/issues/3331

**Comment by hmemcpy** [comment]
Paging @adamgfraser @reibitto for follow-up.

**Comment by bertlebee** [comment]
maybe not just the ZIO Test behaviour, I just tried to run a single test ("is not affected by closing the output stream") in zio/streams-tests/jvm/src/test/scala/zio/stream/ZStreamPlatformSpecificSpec using the plugin and got the whole suite instead of the one test (I added @@ timed and @@ nonFlaky(1000) to the code)

```
+ ZStream JVM - repeated: 1000, 12 s 352 ms (100.00%)
  + Constructors - repeated: 1000, 12 s 352 ms (100.00%)
    + effectAsync
    + effectAsyncMaybe
      + effectAsyncMaybe signal end stream
      + effectAsyncMaybe Some
      + effectAsyncMaybe None
      + effectAsyncMaybe back pressure
    + effectAsyncM
      + effectAsyncM
      + effectAsyncM signal end stream
      + effectAsyncM back pressure
    + effectAsyncInterrupt
      + effectAsyncInterrupt Left
      + effectAsyncInterrupt Right
      + effectAsyncInterrupt signal end stream 
      + effectAsyncInterrupt back pressure
    + fromFile
      + reads from an existing file
      + fails on a nonexistent file
    + fromReader
      + reads non-empty file
      + reads empty file
      + fails on a failing reader
    + fromSocketServer
      + read data
      + write data
    + fromOutputStreamWriter - repeated: 1000, 12 s 352 ms (100.00%)
      + reads what is written - 1 s 532 ms (12.41%)
      + captures errors - 142 ms (1.15%)
      + is not affected by closing the output stream - repeated: 1000, 10 s 668 ms (86.36%)
      + is interruptable - 9 ms (0.08%)
Ran 23 tests in 12 s 223 ms: 23 succeeded, 0 ignored, 0 failed
```

**Comment by hmemcpy** [comment]
Just to make sure, can you run the same from sbt, to see if you get the same results?

**Comment by bertlebee** [comment]
it behaves as expected

streamsTestsJVM/testOnly *.ZStreamPlatformSpecificSpec -- -t "is not affected by closing the output stream"

```
...
[info] Done compiling.
[info] + ZStream JVM - repeated: 2000, 21 s 352 ms (100.00%)
[info]   + Constructors - repeated: 2000, 21 s 352 ms (100.00%)
[info]     + fromOutputStreamWriter - repeated: 2000, 21 s 352 ms (100.00%)
[info]       + is not affected by closing the output stream - repeated: 2000, 21 s 352 ms (100.00%)
[info] Ran 1 test in 22 s 462 ms: 1 succeeded, 0 ignored, 0 failed
```

**Comment by hmemcpy** [comment]
Hmm, interesting. Can you please paste the command line, generated from the IntelliJ test runner? 
![image](https://user-images.githubusercontent.com/601206/94670014-ab208400-031a-11eb-9db0-68e94efbaffb.png)

This entire line (well, not the entire line, just the last part after all the jars)

**Comment by bertlebee** [comment]
... org/scala-sbt/test-interface/1.0/test-interface-1.0.jar:/home/rob/IdeaProjects/zio/streams-tests/shared/target/test-classes:/home/rob/IdeaProjects/zio/streams-tests/shared/target/classes zio.stream.ZStreamPlatformSpecificSpec

**Comment by hmemcpy** [comment]
Hmm, yeah, looks like it doesn't pass the command-line parameters to it. Can you try deleting the run item:
![image](https://user-images.githubusercontent.com/601206/94671289-5ed64380-031c-11eb-924e-133a50e6a9f8.png)
^^ this thing

And try running again, see if it adds the `-t` parameter?

**Comment by bertlebee** [comment]
that didn't fix it, but I'm now almost certain it's related to TestAspects.

runs the suite
```scala
        testM("is not affected by closing the output stream") {
          val data  = Array.tabulate[Byte](ZStream.DefaultChunkSize * 5 / 2)(_.toByte)
          val write = (out: OutputStream) => { out.write(data); out.close() }
          ZStream.fromOutputStreamWriter(write).runCollect.map(assert(_)(equalTo(Chunk.fromArray(data))))
        } @@ nonFlaky(1000),
```
runs the individual test
```scala
        testM("is not affected by closing the output stream") {
          val data  = Array.tabulate[Byte](ZStream.DefaultChunkSize * 5 / 2)(_.toByte)
          val write = (out: OutputStream) => { out.write(data); out.close() }
          ZStream.fromOutputStreamWriter(write).runCollect.map(assert(_)(equalTo(Chunk.fromArray(data))))
        },
```
also tried `@@ timed` with the same result

**Comment by hmemcpy** [comment]
I wouldn't discount this as a bug in the intellij test runner, all it's doing is building the command line to pass into the underlying  `ZStreamPlatformSpecificSpec`, which runs it as a Main app. I'll try reproducing locally. Thanks for the update!

**Comment by bertlebee** [comment]
I've managed to get it to misbehave without the test aspects now. The generated run config appears to be the "Application" type in the run config (red in screen shot) when it's breaking, and a "ZIO Test" config when it works (green in screenshot)
![image](https://user-images.githubusercontent.com/30517573/94674261-40436d00-035b-11eb-805f-e9d8cea4590b.png)
Hope that helps. Bed time for me now.

**Comment by bertlebee** [comment]
Side note, thanks for your quick response!

**Comment by hmemcpy** [comment]
I see. The "Application" kind is the default, which is the "main" app runner. This is what intellij will produce without the ZIO plugin. If you look at this type of items, you'd see parameters you'd expect in the regular "Run application".

The plugin is supposed to replace this item with a "test" item, which has the ZIO logo and properties more suited to a "test" run (ie test class/test method name). I did notice before that sometimes it doesn't replace it.

Try deleting the "Application" item entirely and run one more time. Hopefully, the plugin will create a new one, zio-specific, which will correctly generate the args.

Still, if this doesn't work, I'll look at it.

Also, cheers!

**Comment by bertlebee** [comment]
I deleted all run configurations of any sort when you first suggested deleting one. It didn't appear to work, but it could have just re-triggered whatever underlying issue is causing it not to generate correctly in the first place

**Comment by hmemcpy** [comment]
Closing this until the default filtering in ZIO Test changes.

As for making sure the runner runs only the selected test, it will be handled by #210
