### ISSUE TITLE
Hint to replace with serviceWith.

### ISSUE THREAD

**Issue by octavz** [zio/zio-intellij#301]
Hi, 
```scala    
ZIO.service[Service].flatMap(_.method)
```
can't be replaced with `serviceWith` if `method` has an environment. 

Result should be `ZIO[Has[Service] with ExtraEnv, ...]` while the return env for `serviceWith` is only `Service`.

Thank you,

**Comment by hmemcpy** [comment]
Thank you! Yeah, I goofed up the refactoring, I have another issue about it. Will fix it soon!
In the meantime, you can disable the suggestion:
![image](https://user-images.githubusercontent.com/601206/126641994-92c5ba4b-11f1-400c-ae30-d77ec87d1011.png)

**Comment by octavz** [comment]
np, sorry for not finding the duplicate, you can close it. thanks.
