### ISSUE TITLE
Error adding module to project: Could not parse version: 2.0.0-M1

### ISSUE THREAD

**Issue by subotic** [zio/zio-intellij#303]
When trying to create a new `Scala -> ZIO project (with SBT)` on IntelliJ Ultimate 2021.1.3, I get the following error: `Error adding module to project: Could not parse version: 2.0.0-M1`

![Screenshot 2021-07-28 at 15 22 19](https://user-images.githubusercontent.com/400790/127330349-658ec8f5-d547-41d1-a359-f2c90feef665.png)

This error occurs irrespective of which ZIO version is selected and fails with the same error even if ZIO 1.0.10 is selected:

![Screenshot 2021-07-28 at 15 33 33](https://user-images.githubusercontent.com/400790/127331377-9d7e8807-cce3-44d5-a81d-621a29b42487.png)

IntelliJ Ultimate: 2021.1.3
ZIO for IntelliJ: 2021.1.11.0

**Comment by hmemcpy** [comment]
*sigh*

Thanks. I'll take care of it :(
Hey @timaliberdov, your favorite kind of bug!

**Comment by hmemcpy** [comment]
Thanks for the report! And thanks @timaliberdov for the quick fix! The new version should be available already, please update the plugin. Thanks!

**Comment by subotic** [comment]
Thanks, I can confirm that it works now. Unfortunatelly there is a problem with the created SBT config. I have created a followup issue #307
