### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by cipriandrei10** [zio/zio-intellij#305]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_2.13:1.0.10"
Cause:
org.jetbrains.plugins.scala.DependencyManagerBase$ResolveException: unresolved dependency: dev.zio#zio-test-intellij_2.13;1.0.10: not found
```
### Additional information:
<details>

ZIO plugin version: 2021.2.8.299
Scala plugin version: 2021.2.15
ZIO version(s): 1.0.10
Scala version(s): 2.13.6
sbt version: 1.5.4
IntelliJ version: IntelliJ IDEA 2021.2
Build #IC-212.4746.92
Java version: 11.0.11+9-b1504.13
Operating System: amd64 Windows 10 (10.0, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Thanks for the report! There were some breaking changes in the latest ZIO, so I'd have to adjust the test runner component accordingly. Hopefully very soon!

**Comment by cipriansofronia** [comment]
No worries, I was able to install it in the latest intellij using the early access program
https://plugins.jetbrains.com/plugin/13820-zio-for-intellij/early-access-program-eap

**Comment by hmemcpy** [comment]
Thanks again for the report! The 1.0.10-compatible runner should now be available.
