### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by markusa380** [zio/zio-intellij#308]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_2.12:1.0.10"
Cause:
org.jetbrains.plugins.scala.DependencyManagerBase$ResolveException: unresolved dependency: dev.zio#zio-test-intellij_2.12;1.0.10: not found
```
### Additional information:
<details>

ZIO plugin version: 2021.2.11.1
Scala plugin version: 2021.2.15
ZIO version(s): 1.0.10
Scala version(s): 2.12.13
sbt version: 1.5.5
IntelliJ version: IntelliJ IDEA 2021.2
Build #IC-212.4746.92
Java version: 11.0.11+9-b1504.13
Operating System: x86_64 Mac OS X (11.4, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Thanks for the report! The 1.0.10-compatible runner should now be available.
