### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by evandertino** [zio/zio-intellij#313]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_3:2.0.0-M1"
Cause:
org.jetbrains.plugins.scala.DependencyManagerBase$ResolveException: unresolved dependency: dev.zio#zio-test-intellij_3;2.0.0-M1: not found
```
### Additional information:
<details>

ZIO plugin version: 2021.2.11.1
Scala plugin version: 2021.2.418
ZIO version(s): 2.0.0-M1
Scala version(s): 3.0.1
sbt version: 1.5.5
IntelliJ version: IntelliJ IDEA 2021.2
Build #IU-212.4746.92
Java version: 11.0.11+9-b1504.13
Operating System: x86_64 Mac OS X (11.5.1, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Thanks for the report. Starting ZIO 2.0 the test runner should no longer be required, but the needed PR was not merged into M1 yet. So instead I've disabled the notification for this particular version. In the meantime, you still should be able to run the tests from IntelliJ, but they will be shown in the console output instead...
