### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by agnaldo4j** [zio/zio-intellij#321]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_3:2.0.0-M1"
Cause:
org.jetbrains.plugins.scala.DependencyManagerBase$ResolveException: unresolved dependency: dev.zio#zio-test-intellij_3;2.0.0-M1: not found
```
### Additional information:
<details>

ZIO plugin version: 2021.2.11.1
Scala plugin version: 2021.2.423
ZIO version(s): 2.0.0-M1, 1.0.8
Scala version(s): 3.0.1, 3.0.1
sbt version: 1.5.5
IntelliJ version: IntelliJ IDEA 2021.2
Build #IU-212.4746.92
Java version: 11.0.11+9-b1504.13
Operating System: x86_64 Mac OS X (11.4, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Thanks for the report. Please upgrade to the latest plugin version *and* ZIO 2.0.0-M2, it has the test runner stuff built in!
