### ISSUE TITLE
An unhandled exception occurred in the plugin

### ISSUE THREAD

**Issue by rotemseekingalpha** [zio/zio-intellij#337]
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
com.intellij.diagnostic.PluginException: Short name 'SimplifyUnitInspection' is not unique
class 'zio.intellij.inspections.simplifications.SimplifyUnitInspection' in PluginDescriptor(name=ZIO for IntelliJ, id=zio.intellij.zio-intellij, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5457.46.plugins/zio-intellij, version=2021.2.13.0, package=null)
and class 'zio.intellij.inspections.simplifications.SimplifyUnitInspection' in PluginDescriptor(name=ZIO for IntelliJ, id=zio.intellij.zio-intellij, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5457.46.plugins/zio-intellij, version=2021.2.12.0, package=null)
conflict
```
### Additional information:
<details>

ZIO plugin version: 2021.2.13.0
Scala plugin version: 2021.2.449
ZIO version(s): 
Scala version(s): 
sbt version: 1.5.5
IntelliJ version: IntelliJ IDEA 2021.2.3
Build #IU-212.5457.46
Java version: 11.0.12+7-b1504.40
Operating System: amd64 Linux (5.11.0-38-generic, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Thanks for the report! I seem to get a lot of these today, but I have no idea why :(
For some reason, IntelliJ did not unload the previous version before trying to load the new one... This should typically go away after an IntelliJ restart.

I'll continue investigating. Thanks!
