### ISSUE TITLE
Support methods requiring implicit ev (`NeedsEnv`, `CanFail`)

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio-intellij#346]
In ZIO 2.0 those methods (e.g. `injectSome`) are going through a macro, which means they no longer themselves take implicit parameters. Which makes it statically impossible to prove in order to show the e.g. `InfallibleEffectRecoveryInspection`

One possibility is to create a synthetic member injector and "inject" ZIO with those signatures as if they were still present on the ZIO object. Not sure how this could be resolved, though.

**Comment by myazinn** [comment]
`CanFail` seems to work fine in ZIO 2
 Maybe I'll be able to port `ZIO.provide` machinery to zio-intellij plugin. I've got some progress on it, but not sure if it'll work in the end.

**Comment by hmemcpy** [comment]
I no longer remember right now, but I think there was some talk about depreciating/removing some of the implicits. I admit I'm still not on 2.0 that's why supporting it is so slow! :)

Any help is always appreciated!
