### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by guizmaii** [zio/zio-intellij#354]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_2.13:1.0.13"
Cause:
org.jetbrains.plugins.scala.DependencyManagerBase$ResolveException: unresolved dependency: dev.zio#zio-test-intellij_2.13;1.0.13: not found
```
### Additional information:
<details>

ZIO plugin version: 2021.3.14.1
Scala plugin version: 2021.3.15
ZIO version(s): 1.0.13
Scala version(s): 2.13.7
sbt version: 1.5.2
IntelliJ version: IntelliJ IDEA 2021.3
Build #IU-213.5744.223
Java version: 11.0.13+7-b1751.19
Operating System: x86_64 Mac OS X (12.0.1, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Just published a compatible release! Should be available within 15 minutes or so, the next time you'll reopen the project it should download fine.

Thanks Jules! Closing for now...
