### ISSUE TITLE
`tapBoth` suggested for ZStream

### ISSUE THREAD

**Issue by erikvanoosten** [zio/zio-intellij#358]
`tapBoth` is suggested in the following code:

```
    (ZStream("1", "2", "3") ++ ZStream.fail("a"))
      .tap(i => putStrLn(i).orDie)
      .tapError(e => putStrLn(e).orDie)
```

However, `ZStream` does not have `tapBoth`, so this should not be suggested.

This problem seems related to #202.

**Comment by hmemcpy** [comment]
Hmm, I thought I sent that PR in ZIO to handle ZStreams as well... oh well... thanks, I'll fix it!
