### ISSUE TITLE
ZIO tests not detected in ZIO 2.0 RC5

### ISSUE THREAD

**Issue by elliotford** [zio/zio-intellij#365]
Since the change from `DefaultRunnableSpec` to `ZIOSpecDefault` the tests are not longer considered valid suites. SBT test still works successfully.

Using ZIO 2.0 RC5
Scala 2.13.8

Run arrows do not show on the left:
![image](https://user-images.githubusercontent.com/1975911/166897062-c07dfd7c-6944-454b-b111-7266a0a016be.png)

Tests cannot be selected:
![image](https://user-images.githubusercontent.com/1975911/166897328-7c1e4e21-a986-4408-a4f8-35d9c0b9c410.png)

Not able to run manually by entering in full classname:
![image](https://user-images.githubusercontent.com/1975911/166897244-7f4eebc8-6ff5-4ebb-a31d-aa60b3a04b37.png)

```
IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    org.intellij.scala (2022.1.13)
    zio.intellij.zio-intellij (2022.1.16.0)

Kotlin: 221-1.6.20-release-285-IJ5080.210
```

**Comment by hmemcpy** [comment]
This is now complete, ZIO 2.0 tests should be supported in the test runner.
