### ISSUE TITLE
@accessible annotation doesn't work with newtypes ZIO 2.0 RC5

### ISSUE THREAD

**Issue by elliotford** [zio/zio-intellij#366]
Using the `@accessible` macro works fine for case classes and primitives but if you use newtypes (made by macros) it cannot work out the type of the parameters. It always compiles and runs successfully, it seems to be syntax highlighting + code options.

ZIO 2.0 RC5
Scala 2.13.8

![image](https://user-images.githubusercontent.com/1975911/166897765-ffb9cd46-43c6-4be6-aad3-dd1f02abf2fe.png)

I have not tried to see if the return types are correct.

```scala
  object ClientId extends Newtype[Long]
  type ClientId = ClientId.Type
```

```
IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    org.intellij.scala (2022.1.13)
    zio.intellij.zio-intellij (2022.1.16.0)

Kotlin: 221-1.6.20-release-285-IJ5080.210
```

**Comment by myazinn** [comment]
Hey @Ellzord 
I'm trying to reproduce your issue but it seems like it works ok with estatico newtypes. Could you please specify which library you are using?

```
object ZIO2 {

  import io.estatico.newtype.macros.newtype
  import zio._
  import zio.macros.accessible

  @newtype final case class ClientId(id: Int)

  @accessible
  trait Service {
    def get(id: ClientId): UIO[Unit]
  }

  val clientId: ClientId = ???
  Service.get(clientId)

}
```
![image](https://user-images.githubusercontent.com/28982711/224565604-8b61ab28-e079-47bc-a118-b799f587ebdb.png)

**Comment by myazinn** [comment]
Hey @Ellzord 
I'm trying to reproduce the issue, but it seems to work fine with estatico newtypes. Could you please specify which library you are using?
```scala
import io.estatico.newtype.macros.newtype
import zio._
import zio.macros.accessible

object ZIO2 {

  @newtype final case class ClientId(id: Int)

  @accessible
  trait Service {
    def get(id: ClientId): UIO[Unit]
  }

  val clientId: ClientId = ???
  Service.get(clientId)

}
```
![image](https://user-images.githubusercontent.com/28982711/224566683-b59178fb-9d89-4199-bc7f-662c7f07aedc.png)

**Comment by elliotford** [comment]
@myazinn it was zio prelude. I haven't tried it again since May last year.

```import zio.prelude.Newtype``` https://zio.github.io/zio-prelude/docs/newtypes/

```scala
 object ClientId extends Newtype[Long]
 type ClientId = ClientId.Type
```

**Comment by myazinn** [comment]
@Ellzord works fine 🤔 Could you please somehow check if it's still an issue for you? Maybe it was fixed already
```scala
import zio._
import zio.macros.accessible
import zio.prelude.Newtype

object model {
  object ClientId extends Newtype[Int]
  type ClientId = ClientId.Type
}

import model._

@accessible
trait Service {
  def get(id: ClientId): UIO[Unit]
}

object ZIO2 {
  val clientId: ClientId = ClientId(1)
  Service.get(clientId)
}
```
![image](https://user-images.githubusercontent.com/28982711/224799893-4a6b44c0-7a2d-47dd-9cf4-c6bd0d5dd468.png)

**Comment by myazinn** [comment]
Closing this issue since the problem seems resolved. Feel free to reopen if it appears again

**Comment by elliotford** [comment]
@myazinn I've got the latest version of intellij and I can see this has not been fixed.

![image](https://user-images.githubusercontent.com/1975911/232846251-d5c5e5d4-37f1-4ae9-b34d-abaa9653d03d.png)

In this code the first error is the method is overloaded (Position and Chunk[Position]), the second error it doesn't like the new type and considers it to be Nothing, and in the hover you can see it thinks the return type is Chunk[Any].

![image](https://user-images.githubusercontent.com/1975911/232846629-9946ed89-d78b-44f2-b0ed-f2beb841cbbf.png)


``` 
IntelliJ IDEA 2023.1 (Community Edition)
Build #IC-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    org.intellij.scala (2023.1.16)
    zio.intellij.zio-intellij (2023.1.24.0)

Kotlin: 231-1.8.20-IJ8109.175
```

I'm unable to reopen the issue myself, can you do this for me? If it helps this is in src/test while a previous example it was in src/main.

**Comment by elliotford** [comment]
I can see it's not related to newtypes but just macros + specs.

I'll create a new issue.

**Comment by myazinn** [comment]
Thanks for the report!
Reopening this one as well for better history

**Comment by elliotford** [comment]
@myazinn this can likely be closed too. When can I pick up the update?

**Comment by myazinn** [comment]
@Ellzord I'll make a release tomorrow, so hopefully within 24 hours

**Comment by elliotford** [comment]
Confirmed fixed. Thanks @myazinn

**Comment by myazinn** [comment]
You are welcome :)
