### ISSUE TITLE
Update foreach_ suggestions to foreachDiscard (ZIO 2.0)

### ISSUE THREAD

**Issue by DaniRey** [zio/zio-intellij#385]
With ZIO 2.0 the naming conventions changed and methods like `foreach_` were replaced with `foreachDiscard`

The code suggestions should be updated accordingly

https://zio.dev/guides/migrate/zio-2.x-migration-guide

**Comment by m-kalai** [comment]
i can take this one if that's ok. it's bothering me too anyway 😄

**Comment by hmemcpy** [comment]
Hey! Yeah, any help there would be appreciated! I started working on ZIO2-compatible inspections, but haven't made much progress yet.

There's a function in `ZInspection` called `isAvailable` which takes in the current ZIO version. This could be used to verify if a specific inspection is available. I am okay with duplicating the entire inspection, once for zio1 and once for zio2.

**Comment by m-kalai** [comment]
I created this draft which probably covers the scope of this issue, but i'm having issues with setting up the ZIO2 tests. I was experimenting with changing `zio.inspections.ZInspectionTestBase#versionPattern` but it didn't help. Any ideas @hmemcpy ?

**Comment by hmemcpy** [comment]
Closing as this is fixed! Thanks so much @m-kalai for your contributions!
