### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by jrgvf** [zio/zio-intellij#386]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_2.13:2.0.2"
Cause:
org.jetbrains.plugins.scala.DependencyManagerBase$ResolveException: unresolved dependency: dev.zio#zio-test-intellij_2.13;2.0.2: not found
```
### Additional information:
<details>

ZIO plugin version: 2022.2.17.0
Scala plugin version: 2022.2.13
ZIO version(s): 2.0.2, 1.0.17
Scala version(s): 2.13.8, 2.13.8
sbt version: 1.7.2
IntelliJ version: IntelliJ IDEA 2022.2.1
Build #IC-222.3739.54
Java version: 17.0.3+7-b469.37
Operating System: aarch64 Mac OS X (13.0.1, aarch64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Hmm, your project seems to contain both 1.x and 2.x versions of zio (this confuses the plugin, need to fix that) . For 2.0 you don't need the external test runner to show results in IntelliJ, so I'd make sure all your projects are on 2.0
