### ISSUE TITLE
ZTestRunner can not run zio.test when command line arguments is shortend

### ISSUE THREAD

**Issue by mitsutaka-takeda** [zio/zio-intellij#39]
When IntelliJ IDEA shorten command line arguments, it passes to ZTestRunner a file path in which actual command line arguments are stored.

Current implementation of argument parser does not handle this situation and fails to run test cases.

https://github.com/zio/zio-intellij/blob/993bd54acd893566a437f78b7a5880c33e11ac8c/testrunner_2.12/src/main/scala/zio/intellij/testsupport/runner/ZTestRunner.scala#L10

**Comment by hmemcpy** [comment]
When you say shorten, do you mean one of these options? Which is not the none/default?

![image](https://user-images.githubusercontent.com/601206/75519257-7d353300-5a0b-11ea-8675-7f1af3c02b19.png)

**Comment by mitsutaka-takeda** [comment]
I guess that's the option, but I'm not sure because I don't set the option by myself. IntelliJ Idea asks me to enable the option when test fails due to the length of command line args, and configuration for ZIO Test does not show that options.

When I run ZTestRunner I can see that command line arguments are pass by files like this.

![image](https://user-images.githubusercontent.com/830260/75524235-d96e7600-5a50-11ea-9ddf-84e1bbffe390.png)

So I patched ZTestRunner like scala test runner.

https://github.com/JetBrains/intellij-scala/blob/7aa0fcf807f7401603178cdec011b33f3846f20e/scala/runners/src/org/jetbrains/plugins/scala/testingSupport/TestRunnerUtil.java#L144

**Comment by hmemcpy** [comment]
That's great to know. I'm currently away, will be back next week, so I'll take a look. I'm planning on re-working the test runner launcher to delegate all of the responsibility to the ZIO test itself, so I don't have to handle any additional logic. Thank you for the report!

**Comment by mitsutaka-takeda** [comment]
Thanks!

The limit on the length of command line args is a common issue for Windows users. If some Windows users has the same issue, use this patch. Locally building and installing the plugin fix the issue for me.

https://github.com/mitsutaka-takeda/zio-intellij/commit/9267c0b733ee28555497d9b9149a4863e42d8899

**Comment by hmemcpy** [comment]
@mitsutaka-takeda Sorry for the delays! Thanks again for fixing the issue.
I have separated the test runner into a separate project, external to the plugin. Could you send me a pull request with the fix? I'd like you to get the 'Contributor' badge :)
https://github.com/zio/zio-test-intellij/blob/master/src/shared/src/main/scala/zio/intellij/testsupport/ZTestRunner.scala

**Comment by mitsutaka-takeda** [comment]
Sure! I'll take a look.

**Comment by hmemcpy** [comment]
BTW, I think this is a good fix to include in ZIO itself because the runner is essentially a command-line application.
WDYT @adamgfraser?

**Comment by hmemcpy** [comment]
Closing, as this was fixed upstream. It is still probably an issue in the ZIO test runner itself, need to check if intellij puts the @argFile by default on JVM11+.
