### ISSUE TITLE
Suggest bimap

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-intellij#4]
`.map(a).mapError(b)` => `.bimap(b, a)`
`.mapError(a).map(b)` => `.bimap(a, b)`

**Comment by hmemcpy** [comment]
Hah, I love when features intersect :)
![image](https://user-images.githubusercontent.com/601206/68121023-670cdf80-ff0f-11e9-9f78-1cb345e41535.png)

Possibly need to figure out this and suppress the other suggestion. I guess `bimap` should win.

**Comment by ghostdogpr** [comment]
Yeah bimap will result in one IO loop so it’s better.

**Comment by hmemcpy** [comment]
This makes me thing other combinations might be suggested, such as `.as(a).map/asError` and vice-versa?

**Comment by ghostdogpr** [comment]
Right!

**Comment by hmemcpy** [comment]
Too many options! :D
