### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by erikvanoosten** [zio/zio-intellij#400]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_2.13:2.0.6"
Cause:
org.jetbrains.plugins.scala.DependencyManagerBase$ResolveException: unresolved dependency: dev.zio#zio-test-intellij_2.13;2.0.6: not found---
Download error: zio-test-intellij_2.13:2.0.5"
Cause:
org.jetbrains.plugins.scala.DependencyManagerBase$ResolveException: unresolved dependency: dev.zio#zio-test-intellij_2.13;2.0.5: not found
```
### Additional information:
<details>

ZIO plugin version: 2022.3.20.0
Scala plugin version: 2022.3.18
ZIO version(s): 2.0.6, 1.0.13, 2.0.5
Scala version(s): 2.13.8, 2.12.14, 2.13.8
sbt version: 1.6.1
IntelliJ version: IntelliJ IDEA 2022.3.2
Build #IC-223.8617.56
Java version: 17.0.5+1-b653.25
Operating System: x86_64 Mac OS X (12.6.3, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Yeah, this is an ongoing bug in the ZIO version detection, but looking at the error details, it shows that you have at least one project where you reference ZIO 1.0.13, while the others use ZIO 2.x. The test runner is no longer required for ZIO 2.x, it's built-into ZIO test now. I'll fix the erroneous detection. Thanks!

**Comment by erikvanoosten** [comment]
That is correct. This is project where different modules use different zio versions.
Thanks for fixing!!
