### ISSUE TITLE
warn about nested or unused ZIO

### ISSUE THREAD

**Issue by vitaliis** [zio/zio-intellij#41]
The common pitfall we see is when ZIO is nested in other ZIO. And therefore is not executed.
This problem can have many forms. Thanks to developers and blogs this is already documented and has following forms:
* Case 1 (Writing two ZIO effects without mapping between them) in https://medium.com/wix-engineering/5-pitfalls-to-avoid-when-starting-to-work-with-zio-adefdc7d2d5c
* Case 5 (Using ZIO.Access instead of ZIO.AccessM) and a bit of case 3 in https://medium.com/wix-engineering/5-more-pitfalls-to-avoid-when-starting-to-work-with-zio-d0cdd44fa439

The idea would be to write an inspection that can recognize such lone ZIOs and at least warn about the issue.

**Comment by vitaliis** [comment]
Similar to the scala compiler when it checks for unused vals, but having it one level deeper for ZIO. Unused ZIO expression must be reported.

Just to bring another example. In zio-test when you have something like:
```scala
for {
  ...
} yield {
  assert(true, Assertion.isTrue)
  assert(false, Assertion.isFalse)
}
```
Which is wrong because only the last statement will be considered.
```scala
  assert(true, Assertion.isTrue) &&
  assert(false, Assertion.isFalse)

```
is correct.

**Comment by adamgfraser** [comment]
This would be fantastic if we could figure out a way to do it!

**Comment by hmemcpy** [comment]
This is a great suggestion, and it bit me more than once! Will find a way to do it...

**Comment by hmemcpy** [comment]
Progress :)
![image](https://user-images.githubusercontent.com/601206/80286265-037fa400-8733-11ea-8990-e8242909392c.png)
