### ISSUE TITLE
False negative from inspection for .provideSome

### ISSUE THREAD

**Issue by DaniRey** [zio/zio-intellij#412]
The newly introduced inspections for .provideSome (https://github.com/zio/zio-intellij/pull/396 and https://github.com/zio/zio-intellij/pull/399) might report a problem when there is none.

We use ZIO 2.0.5

![image](https://user-images.githubusercontent.com/7700482/224683926-8964483c-d857-4bbd-a50a-efd3435bd742.png)

```scala
case class DatabaseLive(configService: ConfigService) extends Database {
  ....
}

object DatabaseLive {
  val layer: ZLayer[ConfigService, Nothing, DatabaseLive] = ZLayer {
    for configService <- ZIO.service[ConfigService]
      yield DatabaseLive(configService)
  }
}
```

![image](https://user-images.githubusercontent.com/7700482/224684578-3568a8f8-e84a-41a3-b63a-915dd1ee9e05.png)

**Comment by hmemcpy** [comment]
Oh damn. Thanks for reporting!!

**Comment by hmemcpy** [comment]
Hmm, from first glance, this seems like a subtyping issue. However, I wanted to ask if you intended to specify `DatabaseLive` as your return type in the ZLayer, instead of `Database`? Either way, we'll look into it, thanks again!

**Comment by hmemcpy** [comment]
Ah, right. I still think in terms of "ZIO 1.0" structuring where I would make `live` and `test` layers on the package object instead of the ZIO 2.0-recommended naming of `layer`, and placing it in the companion of the Live/Test implementation. So it would make sense that `layer` exposes the Live concrete implementation directly, versus the interface.

So nevermind ;)

**Comment by myazinn** [comment]
Yep, looks like subtyping issue :( The following snippet reproduces an error
```scala
  trait ConfigService
  case class ConfigServiceLive() extends ConfigService
  object ConfigServiceLive {
    val live: ULayer[ConfigServiceLive] = ???
  }

  trait Database
  case class DatabaseLive(configService: ConfigService) extends Database
  object DatabaseLive {
    val live: ZLayer[ConfigService, Nothing, DatabaseLive] = ???
  }

  val app: URIO[Database, Unit] = ???
  app.provide(DatabaseLive.live, ConfigServiceLive.live)
```
I'll take a look today. Is there any issue with unnecessary `ZIOAppArgs`?

**Comment by DaniRey** [comment]
The `ZIOAppArgs` is necessary in our case, so reporting it as unnecessary is a false negative.

![image](https://user-images.githubusercontent.com/7700482/224690340-81b42658-7226-4812-964b-09799aea3fc4.png)


The ConfigServiceLive looks as follows

```scala
object ConfigServiceLive {
  val layer: ZLayer[ZIOAppArgs, Nothing, ConfigServiceLive] = ZLayer {
    for appArgs <- ZIO.service[ZIOAppArgs]
    yield ConfigServiceLive(appArgs)
  }
}
```

But it might be related to subtyping as well. Because on `ConfigService` we do not have any information about Layer requirements. Which is IMHO correct, as a `ConfigServiceTest` layer might have different requirements, i.e. not needing ZIOAppArgs.

```scala
trait ConfigService {
  def config: IO[Throwable, AppConfig]
}
```

**Comment by myazinn** [comment]
Hmm, then let's fix the known issue and see how it goes. Right now this code is highlighted in red due to subtyping issues
```scala
  trait ConfigService
  case class ConfigServiceLive() extends ConfigService
  object ConfigServiceLive {
    val live: URLayer[ZIOAppArgs, ConfigServiceLive] = ???
  }

  trait Database
  case class DatabaseLive(configService: ConfigService) extends Database
  object DatabaseLive {
    val live: ZLayer[ConfigService, Nothing, DatabaseLive] = ???
  }

  val app: URIO[Database, Unit] = ???
  app.provideSome[ZIOAppArgs](DatabaseLive.live, ConfigServiceLive.live)
```
While this one is not highlighted at all (I've changed return types of ZLayer's)
```scala
  trait ConfigService
  case class ConfigServiceLive() extends ConfigService
  object ConfigServiceLive {
    val live: URLayer[ZIOAppArgs, ConfigService] = ???
  }

  trait Database
  case class DatabaseLive(configService: ConfigService) extends Database
  object DatabaseLive {
    val live: ZLayer[ConfigService, Nothing, Database] = ???
  }

  val app: URIO[Database, Unit] = ???
  app.provideSome[ZIOAppArgs](DatabaseLive.live, ConfigServiceLive.live)
```
So I cannot reproduce this issue for now :(

**Comment by DaniRey** [comment]
I wonder if it is an Intellij or Scala 3 issue, because Intellij somehow thinks `app` is of type `ZIO[Any, Throwable, Unit]`, even when I explicitly type it (I used the XYZLive to avoid the subtyping issue)

![image](https://user-images.githubusercontent.com/7700482/224700167-e8502c36-8755-4bac-a7ea-1820cb096194.png)

**Comment by hmemcpy** [comment]
Are you using Scala 3? I'd blame IntelliJ :)

**Comment by hmemcpy** [comment]
I definitely need to learn to read. If this is Scala 3 - I'd say this is an IntelliJ bug.

**Comment by myazinn** [comment]
@DaniRey thanks for the report! Fix for this issue is merged, should be ok soon

**Comment by hmemcpy** [comment]
Cheers! I will backport this to 2022.x and will release it shortly!

**Comment by DaniRey** [comment]
Thanks @myazinn and @hmemcpy for this crazy fast support and resolution

**Comment by hmemcpy** [comment]
Just submitted the fixes to JetBrains. Hopefully it will be up soon! <3

**Comment by DaniRey** [comment]
I investigated further what's going on with the false negative "You have provided more arguments to provideSome than is required."

I'm quite sure it is an Intellij Bug. Intellij wrongly assumes the type of app to be `ZIO[Any, Throwable, Unit]` while it should be `ZIO[ConfigService & FileSystem & Database, Throwable, Unit]` or `ZIO[ConfigService with FileSystem with Database, Throwable, Unit]`. My understanding is, that with Scala 3 the intersection type is the way to go for ZIO layers. Then by providing `ConfigServiceLive` the additional requirement for `ZIOAppArgs` is introduced.

If I add the following type definition `ZIO[ConfigServiceLive with FileSystemLive with DatabaseLive, Throwable, Unit]` (using ...Live explicitly to avoid the sub-typing issue), no warning is produced.

I suspect the Intellij issue is caused by intersection and union types not yet being implemented https://youtrack.jetbrains.com/issue/SCL-15028/support-intersection-types.

It is great that the inspection is already aware of layer requirements added by the providing a layer, as with my ConfigServiceLive implementation requiring ZIOAppArgs.

**Comment by myazinn** [comment]
@DaniRey thanks!
I'll check if we can fix it on our side. Maybe we'll disable this warning for Scala 3 so that it wouldn't annoy everyone until supported by Intellij
