### ISSUE TITLE
New ZIO project Wizard is broken in IntelliJ 2023.1 - does not complete

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio-intellij#414]
It's probably better to rewrite it using the new project wizard API (see #331)

**Comment by myazinn** [comment]
I've tried to create a project in Intellij 2023.1 (release) and it has worked fine 🤔 

Also, I've tried to use new wizard API the dumb way, and the result is not what I'd expect. Looks like we'll have to add ZIO wizard on a new general screen and place ZIO version dropdown _somewhere_ somehow (clearly not as a build system), which might look awkward.
![image](https://user-images.githubusercontent.com/28982711/230788678-f1c7754b-3450-4ada-8898-89ee85fcf56c.png)
Will take a look at how it's done for other generators, but if they are not using new wizard API, then I'm not sure how we should rewrite to use a new API (or should we do it at all).

**Comment by hmemcpy** [comment]
Ah right, I forgot to update - I think the problem might actually be the Copilot plugin! It causes something in the project wizard not to work.

Also, yeah, the old project wizard API will probably be removed one day, so we need to migrate to the new one.
I think I opened this issue a few years ago :P #331

**Comment by hmemcpy** [comment]
Closing as complete! I implemented the New Project Wizard in #471
