### ISSUE TITLE
@accessible macro highlights as error but runs in tests

### ISSUE THREAD

**Issue by elliotford** [zio/zio-intellij#429]
@myazinn I've got the latest version of intellij and I can see this has not been fixed.

![image](https://user-images.githubusercontent.com/1975911/232846251-d5c5e5d4-37f1-4ae9-b34d-abaa9653d03d.png)

In this code the first error is the method is overloaded (Position and Chunk[Position]), the second error it doesn't like the new type and considers it to be Nothing, and in the hover you can see it thinks the return type is Chunk[Any].

![image](https://user-images.githubusercontent.com/1975911/232846629-9946ed89-d78b-44f2-b0ed-f2beb841cbbf.png)

``` 
IntelliJ IDEA 2023.1 (Community Edition)
Build #IC-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    org.intellij.scala (2023.1.16)
    zio.intellij.zio-intellij (2023.1.24.0)

Kotlin: 231-1.8.20-IJ8109.175
```

I'm unable to reopen the issue myself, can you do this for me? If it helps this is in src/test while a previous example it was in src/main.

_Originally posted by @Ellzord in https://github.com/zio/zio-intellij/issues/366#issuecomment-1513486355_

**Comment by elliotford** [comment]
![image](https://user-images.githubusercontent.com/1975911/232865712-e77640fe-4a3c-45d2-b9cc-1ed31cbc7181.png)
![image](https://user-images.githubusercontent.com/1975911/232865760-1e3a2245-db49-4f46-93ee-1e10f72c0a8c.png)
![image](https://user-images.githubusercontent.com/1975911/232865888-71fba9eb-f527-4949-97c1-1fb2bfa13f2d.png)

**Comment by hmemcpy** [comment]
Thanks so much for the reports! I'll try looking into this as well, though I admit the macro stuff is black magic to me!

But a question: is `Postgres.tenants` (and its implicit context, etc) something in your code base, or is it a part of some library?

**Comment by elliotford** [comment]
@hmemcpy it's part of my code base. Playing around with aspects to make my postgres tests easier to write/reason about

**Comment by elliotford** [comment]
It looks like I get the same issues in src/main too. Is there anything else I can add to help diagnosing this?

**Comment by myazinn** [comment]
@Ellzord I'll take a look today or tomorrow and will come back to you

**Comment by myazinn** [comment]
I've tried to make my code as close as possible to yours but it still works fine 🤔 
```scala
import zio._
import zio.macros.accessible
import zio.prelude.Newtype

object model {
  object PositionId extends Newtype[Int]
  type PositionId = PositionId.Type

  object EventId extends Newtype[Int]
  type EventId = EventId.Type

  final case class Context(value: Int)
  final case class Position(value: Int)
}

import model._

@accessible
trait Repository {
  def save(Position: Position)(implicit context: Context): UIO[PositionId]
  def save(Positions: Chunk[Position])(implicit context: Context): UIO[Chunk[PositionId]]
  def findByEventId(eventId: EventId)(implicit context: Context): UIO[Chunk[Position]]
}

object Repository {
  val live = ???
}

object ZIO2 {
  implicit val context: Context = Context(1)

  for {
    _ <- Repository.save(Position(1))
    _ <- Repository.save(Chunk(Position(1)))
    _ <- Repository.findByEventId(EventId(1))
  } yield ()

}
```
Could you please check if the code above is highlighted? If not, it'll be really great if you could simplify and share your code in scastie, because I'm out of ideas on how to reproduce it

**Comment by elliotford** [comment]
[GitHubBug.zip](https://github.com/zio/zio-intellij/files/11314522/GitHubBug.zip)

@myazinn I've made an example project that shows the problem. It turns out it's related to having different modules. When I try your example in one module it all works fine but if I split it up I get the errors.

I've attached the project in a zip. Is that okay?

**Comment by myazinn** [comment]
That's awesome, thank you! I'll take a look today

**Comment by myazinn** [comment]
@Ellzord yes, now I can see errors
Turns out it's not related to newtypes nor different modules. It's happenning because model case classes are defined within package object. Thanks again for the report! I'll try fixing it soon.

Also, just in case here's a minimized code snippet that reproduces the issue
```scala
// separate package object
package bug

package object plugin {
  final case class UserId(id: Int)
}

// another file
package bug.plugin

import zio.UIO
import zio.macros.accessible

@accessible
trait Repo {
  def find(id: UserId): UIO[Unit]
}

object Test extends App {
  println(Repo.find(UserId(1)))
}
```
