### ISSUE TITLE
When using "suiteAll" only last test is shown as took into consideration by IDE

### ISSUE THREAD

**Issue by arcilli** [zio/zio-intellij#434]
When using `suiteAll`, only the last test is highlighted as being taken into consideration. The compiler suggest that the others are ignored, which is not the case.

Expected result: no tests are greyed out, since they're all executed
Plugin version: 2023.1.24.0

![image](https://user-images.githubusercontent.com/21256988/234653536-c030a2c9-d7b6-4496-beb9-8934f0d2888c.png)

However, on `sbt test`, it behaves normally, running all the tests.

**Comment by myazinn** [comment]
Hmm, didn't know such macro exists 🤔 Thanks, will fix!

**Comment by hmemcpy** [comment]
Same, didn't know about `suiteAll`! Thanks for the heads-up!
