### ISSUE TITLE
Problem downloading the test runner

### ISSUE THREAD

**Issue by lancewalton** [zio/zio-intellij#446]
The following error(s) occurred while downloading the ZIO Test runner files:

```
Download error: zio-test-intellij_2.13:2.0.13"
Cause:
org.jetbrains.plugins.scala.DependencyManagerBase$ResolveException: unresolved dependency: dev.zio#zio-test-intellij_2.13;2.0.13: not found
```
### Additional information:
<details>

ZIO plugin version: 2023.1.25.0
Scala plugin version: 2023.1.547
ZIO version(s): 2.0.13, 1.0.17, 1.0.18, 1.0.18
Scala version(s): 2.13.10, 2.13.10, 2.13.10, 2.12.17
sbt version: 1.8.2
IntelliJ version: IntelliJ IDEA 2023.1.1
Build #IC-231.8770.65
Java version: 17.0.6+10-b829.9
Operating System: x86_64 Mac OS X (13.3.1, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

**Comment by hmemcpy** [comment]
Hey. This is an erroneous message that happens because there are mixed ZIO versions in the project (it seems you have both 1.x and 2.0). I just fixed the notification, it won't show in future versions, but you should look in your build.sbt to make sure you're aligned on one ZIO version!

**Comment by hmemcpy** [comment]
Closing for now.

**Comment by lancewalton** [comment]
Yes, I’m working in a mono-repo where not all modules have been migrated to ZIO2 yet, so that makes sense.

Thank you.

Lance
