### ISSUE TITLE
Idea 2020.1 support

### ISSUE THREAD

**Issue by MaT1g3R** [zio/zio-intellij#45]
I see that there's a PR for idea 2020.1 support https://github.com/zio/zio-intellij/pull/32,
can we publish a new version to the marketplace?

![image](https://user-images.githubusercontent.com/15258494/78956789-69242d00-7ab1-11ea-91b1-691f4284f689.png)

**Comment by hmemcpy** [comment]
Unfortunately, the plugin is currently broken for RC18, I need to fix it before I can push a new version. I'll tend to it very soon!

**Comment by hmemcpy** [comment]
This is now fixed! https://twitter.com/hmemcpy/status/1252193495122657280

**Comment by MaT1g3R** [comment]
Is it released to the marketplace?

**Comment by hmemcpy** [comment]
It was released this morning. Can you try running 'Check for updates?'
If it still doesn't show, what's the exact version of the IDE you're using? (copy from the about screen)

**Comment by MaT1g3R** [comment]
Check for updates didn't work for some reason, I restarted IntelliJ and it worked
