### ISSUE TITLE
Link to open intellij diff view for failed assertions

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-intellij#461]
The Scalatest integration offers this link in the test result, that lets you open the diff view of intellij to compare expected and actual value of an assertion, if the assertion failed.

Such a feature would be a great improvement. I think this is a generic intellij feature. But I could not find a way to trigger this.

![Screenshot 2023-12-17 at 08 50 08](https://github.com/zio/zio-intellij/assets/7283535/a2e9ea24-c092-4f2d-bb24-902696b1d992)

**Comment by hmemcpy** [comment]
Very cool suggestion! Should be doable, I'll look into it. Thanks!
