### ISSUE TITLE
SuggestTypeAlias is missing a dot

### ISSUE THREAD

**Issue by nafg** [zio/zio-intellij#463]
I'm getting things like `zioURIO[...`. There should be a dot between `zio` and the alias.

**Comment by hmemcpy** [comment]
ugh. I hadn't encountered it. Can you paste a small snippet where you're trying to invoke this refactoring?
Also, is this Scala 2 or 3? and what ZIO version?

**Comment by nafg** [comment]
Scala 2, ZIO 2.x

I don't have a snippet this second but it was consistent. I think it was on method return types.

**Comment by hmemcpy** [comment]
Cheers, I'll take a look. Thanks!

**Comment by hmemcpy** [comment]
I was able to reproduce this, going e.g. from `ZIO[Any, Exception, Unit]` to `IO[Exception, Unit]` in both ZIO 1 and ZIO 2 projects. Hmm. Let's see...

**Comment by hmemcpy** [comment]
A quick look suggests that the canonical text for the type alias returns `_root_.zioIO` for some reason. This is from the Scala plugin itself, they may have introduced a bug. Will have to bisect. *sigh*

**Comment by hmemcpy** [comment]
Well, I found the relevant change in the Scala plugin (https://github.com/JetBrains/intellij-scala/commit/0669994c02f3eb15d9c67f09f9c696227c83060f). Will continue after the holidays to figure out what/why it was changed. Will try to think of a hack as a workaround in the meantime...

**Comment by hmemcpy** [comment]
Welp, in the meantime I've merged in a hack. This should be available later in the EAP channel. I'll see if I get a better answer from the JetBrains folks regarding solving this.
