### ISSUE TITLE
Expected and actual values are swapped for "Click to see difference"  report

### ISSUE THREAD

**Issue by vladimirkl** [zio/zio-intellij#465]
Hi, just noticed that new "Click to see difference" feature reports expected and actual values in wrong order:
```scala
  def spec = test("fail") {
    val xs = List(1, 2, 3)
    assertTrue(xs.length == 2)
  }
```
```
Assertion failed:
Expected :3
Actual   :2
<Click to see difference>

  ✗ 3 was not equal to 2
  xs.length == 2
  .length = 3
  xs = List(1, 2, 3)
```

**Comment by hmemcpy** [comment]
Yeah, my bad, sorry :D
Fixed this in commit 099e1ae7019ed14644a3b4ea85524adf71146fc7
The fixed version should be available soon. Thanks!
