### ISSUE TITLE
Suggest IO.none or IO.some

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-intellij#5]
`IO.succeed(None)` => `IO.none`
`IO.succeed(Some(a))` => `IO.some(a)`

**Comment by hmemcpy** [comment]
Are you sure this is right? `IO.succeed(None)` and `IO.none` do not seem to return the same type:
(and now, thanks to my newest addition:)
This is `IO.succeed(None)`:
![image](https://user-images.githubusercontent.com/601206/68624666-03bb1880-04e0-11ea-9c6f-c307074f5dc3.png)

And this is `IO.none`:
![image](https://user-images.githubusercontent.com/601206/68624701-19304280-04e0-11ea-8b3c-f85aa326b1b5.png)

**Comment by adamgfraser** [comment]
Yes this is right. `None` is identical to `Option[Nothing]`.

```scala
sealed trait Option[+A]

final case class Some[+A](value: A) extends Option[A]
case object None extends Option[Nothing]
```

We can see that `None` extends `Option[Nothing]`. Furthermore, `None` is the only instance of `Option[Nothing]` that can exist. There can't be a `Some[Nothing]` because that would require a `value` of type `Nothing` to exist and there are no such values.

**Comment by hmemcpy** [comment]
Right, but then `IO.succeed(None)` has a different meaning here, expecting to return the singleton `None.type`, so they aren't really interchangeable.

**Comment by adamgfraser** [comment]
I'm not sure I follow. Here is the implementation of `ZIO.none`:

```scala
  /**
   * Returns an effect with the empty value.
   */
  final val none: UIO[Option[Nothing]] = succeed(None)
```

**Comment by hmemcpy** [comment]
Yeah, you're right. When it tries to infer the type of `IO.succeed(None)`, it is generating `UIO[None.type]` by default. Manually changing it to `UIO[Option[Nothing]` obviously works, but if left as `UIO[None.type]` then changing to `IO.none` won't compile.

Edit: this seems to be the default scala behavior, I tried in ammonite:
```scala
@ def foo[A](a: A) = Option(a)
defined function foo

@ foo(None)
res2: Option[None.type] = Some(None)
```

I'll think about how to approach this

**Comment by hmemcpy** [comment]
I'll commit the fix for now, will handle the mismatched types later.
