### ISSUE TITLE
Suggest IO.when

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-intellij#6]
`if (a) b else IO.unit)` => `IO.when(a)(b)`

**Comment by hmemcpy** [comment]
Is it always `IO.when`? Or should the type be the same as the `.unit` type? E.g. `ZIO.unit` -> `ZIO.when` and `Task.unit` -> `Task.when`?

**Comment by ghostdogpr** [comment]
I think it should be the type of `b`. If it’s not doable you could always use `ZIO.when`.

**Comment by hmemcpy** [comment]
Ok, this is easier then :)

**Comment by hmemcpy** [comment]
Wait, shouldn't this be simply `b.when(a)`?

**Comment by ghostdogpr** [comment]
Yeah it’s the same. Personally I prefer having `when` first because it reads better. Being at the end, it’s easy to miss it.
