### ISSUE TITLE
Detect erroneous use of Nothing in the contravariant position

### ISSUE THREAD

**Issue by hmemcpy** [zio/zio-intellij#64]
i.e. 
```scala
trait S {
  def foo: ZIO[Nothing, Nothing, Unit]
                 ^
                 |--------- most certainly a mistake
}

**Comment by adamgfraser** [comment]
I would be careful that you only do this for certain types. In some cases this can be valuable to indicate an effect that cannot receive an input. For example:

```scala
type Dequeue[+A] = ZQueue[Any, Nothing, Any, Nothing, Nothing, A]
```

**Comment by hmemcpy** [comment]
Ooh, good point! I'll think carefully about this!

**Comment by hmemcpy** [comment]
I could do a nasty hack, and check whether the type parameter is named `R` (or `R*`), which would obviously be enforced for ZIO types. But for starters, just covering `ZIO` (and its R-aliases) should be enough.

**Comment by adamgfraser** [comment]
I think the heuristic you could use is to issue a warning if you can't do anything with that data type with the paramater as `Nothing`. So like using it with `ZIO`, `ZManaged`, or `ZStream` would be erroneous, whereas it would not be erroneous with any type parameter of `ZQueue`.
