### ISSUE TITLE
Suggest ZIO type aliases

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-intellij#7]
Could be nice to suggest type aliases like if there is `ZIO[Any, Nothing, A]`, suggest `UIO[A]`.

**Comment by poslegm** [comment]
It will be **very** useful!

**Comment by hmemcpy** [comment]
This was a bit tricky to get, but I think it's working now :)
Will need to test it a bit more. Also, need to figure out how to sort this suggestion list. Right now it's sorted by length, which may not be ideal. I might be able to query IntelliJ to see which type aliases are most used by the user's code, and take it into consideration. Or maybe not :D

![Nov-10-2019 14-24-31](https://user-images.githubusercontent.com/601206/68543941-530d2600-03c6-11ea-9aff-1f0636740a42.gif)

**Comment by ghostdogpr** [comment]
Length sounds good to me since you usually want the simplest form you can 👍
