### ISSUE TITLE
"Replace with .unit" replacing too much code

### ISSUE THREAD

**Issue by reibitto** [zio/zio-intellij#78]
Sometimes the `.unit` suggestion is replacing too much code. Here's a minimal example:

```scala
UIO(println("a")) *> UIO(println("b")).unit
```

It gets replaced with:

```scala
UIO(println("a")).unit
```

This is with 2020.1.0.5.

**Comment by hmemcpy** [comment]
Hmm, that's certainly not good. Will check, thanks!
Also better make sure the other replacements don't suffer from the same issue...
