### ISSUE TITLE
Wrong suggestion fromOption

### ISSUE THREAD

**Issue by octavz** [zio/zio-intellij#80]
Given:

```scala
val a: Task[Option[Int]] = ZIO(Option(1))
```
it suggests `ZIO.fromOption` which is obviously wrong since the `fromOption` will return an `IO[Unit,...]` and initial code is `IO[Throwable,...]`

**Comment by hmemcpy** [comment]
Hmm, you're right, the check is currently "too" aggressive, I should tweak it to consider such cases with an explicit type annotation. Thanks!

**Comment by hmemcpy** [comment]
I made the change that checks whether the value has an explicit type annotation. However, it won't work inside for-comprehensions:

`val a: Task[Option[Int]] = ZIO(Option(1))` - won't suggest
`val a = ZIO(Option(1))` - will suggest
`for {
  a <- ZIO(Option(1) 
  ...
` - will suggest

I may be able add an additional check for a type ascription inside a for-comprehension, but those are very rare and it will look awkward.

My question is: what is your usecase? Why wrap an Option in ZIO? I'd like to know if there's a scenario I'm not thinking of.

**Comment by vpavkin** [comment]
I think it might still be too aggressive :)
I have this code highlighted:

![image](https://user-images.githubusercontent.com/410508/85375417-f1f22700-b53e-11ea-91d5-34347f6f6e94.png)

It's not even wrapping an option in the end :)

**Comment by hmemcpy** [comment]
@vpavkin hmm, certainly seems wrong :) Will fix.
