### ISSUE TITLE
Wrong autofix for `.when` method

### ISSUE THREAD

**Issue by myazinn** [zio/zio-intellij#81]
Example
```
def list: List[Int] = ???
def toZio: Int => UIO[Int] = ???

for {
  _ <- if (true) ZIO.foreach_(list)(toZio) else ZIO.unit
} yield ???
```
Plugin correctly suggests using the `.when` method, but incorrectly transforms `for comprehension` into
```
for {
  _ <- ZIO.foreach_(ZIO.foreach_(list)(toZio)).when(true)
} yield ???
```

**Comment by timaliberdov** [comment]
Hmm.. Actually simplification of `if (true) ZIO.foreach_(list)(toZio) else ZIO.unit` is incorrect even outside of for. I'll take a look. Thanks!
