### ISSUE TITLE
"Replace with .unit" inspection replaces too much

### ISSUE THREAD

**Issue by vitaliis** [zio/zio-intellij#85]
Here is a short example of code that demonstrates that:

```scala
(zio.console.putStrLn("Hello") *> zio.console.putStrLn("world").unit).as(0)
```
After applying the suggestion we get:
```scala
zio.console.putStrLn("Hello").unit.as(0)
```
which has a different meaning than the initial expression.

**Comment by vitaliis** [comment]
And to give you more context. In this case `putStrLn` actually returns Unit. But the same replacement is true for other return types. In my case it was `fiber1.interrupt *> fiber2.interrupt.unit` that was replaced with `fiber1.interrupt.unit`, which is not equivalent.

**Comment by hmemcpy** [comment]
I'm sure this is the same as #78 which I already fixed but haven't released the version yet. I'll take care of this. Thanks for reporting!

**Comment by vitaliis** [comment]
Ah, right! I searched for unit, but only among open issues :)
