### ISSUE TITLE
ZIO.service fix is wrong

### ISSUE THREAD

**Issue by octavz** [zio/zio-intellij#98]
Having:
   ```
    ZIO.access[Has[XXX]](_.get)
``` 
it recommends correctly to use `ZIO.service` however it fixes it with:
```
ZIO.service[Has[XXX]]

``` 
while it should have been `ZIO.service[XXX]`

**Comment by timaliberdov** [comment]
Thanks for reporting! Please take a look at #96. It should be fixed by #97.

**Comment by hmemcpy** [comment]
I'll release a fix shortly, it should be available in the gallery in the next day or two

**Comment by octavz** [comment]
sorry, it was a fresh install so I thought the bug is either new or not reported, and didn't search much, I will close. ty,
